#!/bin/sh
# Environment variables go here.

# TERM
#export TERM="xterm-256color"

# HOME cleanup
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"

# zsh
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export HISTSIZE=10000
export SAVEHIST=10000
# zoxide
export _ZO_DATA_DIR=${XDG_DATA_HOME:-$HOME/.local/share}

# pkg-config (needed for postgresql@13 for brightfunds)
export PKG_CONFIG_PATH="/usr/local/opt/postgresql@13/lib/pkgconfig"

# wm
export CWMRC="${XDG_CONFIG_HOME:-$HOME/.config}/cwm/.cwmrc"

# Defaults
export EDITOR="emacs"
#if [ $USER = "meep" ]; then
#    export TERMINAL="termite"
#else
#    export TERMINAL="alacritty"
#fi
export BROWSER="brave"
export SCROTS="$HOME/pics/scrots"

# Qt applications styling
export QT_STYLE_OVERRIDE=kvantum

## PATH and all the other env crap that gets initialized
# pyenv
export PYENV_ROOT="$HOME/.pyenv"

# PATH 
export PATH="/bin:/sbin:/usr/local/sbin/:/usr/local/bin:/usr/bin:$HOME/.local/bin:$HOME/.emacs.d/bin:$HOME/.local/bin/fnm:/usr/local/opt/postgresql@13/bin:$HOME/.rbenv/bin:$HOME/.cargo/bin:$PYENV_ROOT/bin"
