#!/bin/sh

# X settings
xset s off
xset dpms 0 0 0
xsetroot -cursor_name left_ptr &

# startup apps
dunst &
nm-applet &
if [ $(hostname) = "stinky" ]; then
    blueman-applet &
fi
wmname LG3D
keepassxc &
megasync &
syncthing &

# startup script
startup
